### ISSUE TITLE
Question - configuring token at system level.

### ISSUE THREAD

**Issue by 274188A** [lsgs/redcap-rest#1]
Hi Luke (@lsgs),

Just getting familiar with this EM as I might be using it soon.

![image](https://github.com/user-attachments/assets/9c95a1eb-1772-4203-bbe7-10c23f8f4fe1)

I've not used the '[token-ref]' tag before so not sure how one is actually created at system level - any pointers?

Thanks,

John

**Comment by lsgs** [comment]
Take a look in the EM settings in the Control Center and you'll see you can create repeating subsettings like this, @274188A:

![image](https://github.com/user-attachments/assets/87e22c65-4204-424f-90cd-b56f13226b99)

The idea is that you as admin can record private information such as auth tokens here at system level so they are not visible to project users when embedded in project-level settings. Indeed, if it is a project API token for a particular user that you want to use, then select the project and user and no-one need ever actually see the user's token.

Say you configure a system-level token reference of `secret-auto-token` , then you can use `[tokn-ref:secret-auth-token]` in your project config whereever you would otherwise hard-code the auth token - typically in the payload or additional headers.
HTH

**Comment by 274188A** [comment]
ah! missed that - thanks!
